### ISSUE TITLE
🛑 Cybotrade is down

### ISSUE THREAD

**Issue by cybotrade** [cybotrade/status#1]
In [`b707abb`](https://github.com/cybotrade/status/commit/b707abb18e64c95ffb47000acf622412199b7e74
), Cybotrade (https://app.cybotrade.rs) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by cybotrade** [comment]
This should just be a false alarm, no incident happened last night except for production deployment. So it might be caused during that few seconds - mins of production deployment

**Comment by marcustut** [comment]
On a second though, I think this might be due to our website is responding very slow, when I go to `app.cybotrade.rs` I can notice that the Time to First Load (TTFL) is very slow and perhaps because of that it has timed out when `Upptime` tries to call it.
